name: Deploy to neocities

on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 1
  node_version: 16

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Set up any tools and build steps here
    # This example uses a Node.js toolchain to build a site
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node_version }}
    - run: npm i
    - run: npm run build
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v1.1.15
      with:
        cleanup: false
        dist_dir: site
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}